version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  backend-tests:
    docker:
      - image: cimg/node:18.17.0
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: src/backend
      - run:
          name: Lint Backend
          command: cd src/backend && npm run lint
      - run:
          name: Run Backend Tests with Coverage
          command: cd src/backend && npm test -- --coverage
      - run:
          name: Build Backend
          command: cd src/backend && npm run build
      - store_artifacts:
          path: src/backend/coverage
          destination: backend-coverage
      - store_artifacts:
          path: src/backend/test-results
          destination: backend-test-results

  frontend-tests:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: src/frontend
      - run:
          name: Lint Frontend
          command: cd src/frontend && npm run lint
      - run:
          name: Run Frontend Tests with Coverage
          command: cd src/frontend && npm test -- --coverage
      - run:
          name: Build Frontend
          command: cd src/frontend && npm run build
      - store_artifacts:
          path: src/frontend/coverage
          destination: frontend-coverage

  ui-tests:
    docker:
      - image: cimg/node:18.17.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages:
          pkg-manager: npm
          app-dir: src/frontend
      - run:
          name: Install Playwright
          command: cd src/frontend && npx playwright install --with-deps
      - run:
          name: Run Playwright Tests
          command: cd src/frontend && npx playwright test
      - store_artifacts:
          path: src/frontend/playwright-report
          destination: playwright-report
      - store_artifacts:
          path: src/frontend/test-results
          destination: playwright-traces

workflows:
  version: 2
  build-test:
    jobs:
      - backend-tests
      - frontend-tests
      - ui-tests:
          requires:
            - backend-tests
            - frontend-tests
