version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/project
jobs:
  install-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd src/backend
            npm install
      - save_cache:
          paths:
            - src/backend/node_modules
          key: backend-npm-cache-{{ checksum "src/backend/package-lock.json" }}
  install-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd src/frontend
            npm install
      - save_cache:
          paths:
            - src/frontend/node_modules
          key: frontend-npm-cache-{{ checksum "src/frontend/package-lock.json" }}
workflows:
  version: 2
  install-dependencies:
    jobs:
      - install-backend
      - install-frontend