---
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'src/backend/package-lock.json'
      - name: Install Backend Dependencies
        run: |
          cd src/backend
          npm ci
      - name: Lint Backend
        run: |
          cd src/backend
          npm run lint
      - name: Run Backend Tests with Coverage
        run: |
          cd src/backend
          npm test -- --coverage
      - name: Build Backend
        run: |
          cd src/backend
          npm run build
      - name: Upload Backend Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage
          path: src/backend/coverage/
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: src/backend/test-results/

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'src/frontend/package-lock.json'
      - name: Install Frontend Dependencies
        run: |
          cd src/frontend
          npm ci
      - name: Lint Frontend
        run: |
          cd src/frontend
          npm run lint
      - name: Run Frontend Tests with Coverage
        run: |
          cd src/frontend
          npm test -- --coverage
      - name: Build Frontend
        run: |
          cd src/frontend
          npm run build
      - name: Upload Frontend Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-coverage
          path: src/frontend/coverage/

  ui-tests:
    runs-on: ubuntu-latest
    needs: [frontend-tests, backend-tests]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'src/frontend/package-lock.json'
      - name: Install Playwright
        run: |
          cd src/frontend
          npm ci
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd src/frontend
          npx playwright test
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: src/frontend/playwright-report/
      - name: Upload Playwright Traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: src/frontend/test-results/
